03 多次元配列の計算
================

## 1. 多次元配列

* `多次元配列`とは、簡単に言うと「数字の集合」

* まず、1次元の配列を見てみる

In [1]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [2]:
np.ndim(A)

1

In [3]:
A.shape

(4,)

In [4]:
A.shape[0]

4

* 配列の次元数は、`np.ndim()`関数で取得できる

* 配列の形状は、インスタンス変数の`shape`から取得できる

    * `shape`では、タプルで返される

* 続いて、2次元の配列を作成する

In [5]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
np.ndim(B)

2

In [7]:
B.shape

(3, 2)

\begin{pmatrix}
1 & 2 \\
3 & 4  \\
5 & 6
\end{pmatrix}

## 2. 行列の積

* `np.dot`は、行列の積を計算する

    * 1次元配列の場合はベクトル、2次元配列の場合は行列の積を計算する
    
    * ただし、`np.dot(A, B)`と`np.dot(B, A)`は異なる値となる

In [8]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [9]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [10]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

\begin{eqnarray}
\begin{pmatrix}
1 & 2 \\
3 & 4 \end{pmatrix}
\begin{pmatrix}
5 & 6 \\
7 & 8 \end{pmatrix}
=
\begin{pmatrix}
19 & 22 \\
43 & 50\end{pmatrix}
\end{eqnarray}

* 次に、$2 \times 3$の行列と、$3 \times 2$の行列の積を実装する

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [12]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [13]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

\begin{eqnarray}
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \end{pmatrix}
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 \end{pmatrix}
=
\begin{pmatrix}
22 & 28 \\
49 & 64\end{pmatrix}
\end{eqnarray}

* ただし、「行列の形状(`shape`)」には注意する

    * 行列`A`の1次元目の要素数と、行列`B`の0次元目の要素数(行数)を同じ値にする必要がある
    
    * もし異なっていると、以下の用意エラーが発生する

In [15]:
C = np.array([[1, 2], [3, 4]])
C.shape

(2, 2)

In [16]:
A.shape

(2, 3)

In [17]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

\begin{eqnarray}
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \end{pmatrix}
\begin{pmatrix}
1 & 2 \\
3 & 4 \end{pmatrix}
=
計算できない
\end{eqnarray}

* ただし、以下の通りに変更することで、計算ができるようになる

In [18]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [19]:
B = np.array([7,8])
B.shape

(2,)

In [20]:
np.dot(A, B)

array([23, 53, 83])

\begin{eqnarray}
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 
\end{pmatrix}
\begin{pmatrix}
7 & 8 
\end{pmatrix}
=
\begin{pmatrix}
23 & 53 & 83
\end{pmatrix}
\end{eqnarray}

## 3. ニューラルネットワークの行列の積

* ここでは、以下の図を用いたニューラルネットワークを対象として、NumPy行列を使って実装を行う

    * ただし、このニューラルネットワークは、バイアスと活性化関数は省略し、重みだけがあるものとする

![NNを行列の式で表す](./images/NNを行列の式で表す.png)

* 実装に関しては、$X$、$W$、$Y$の形状に注意する

    * 特に、$X$と$W$の対応する次元の要素数が一致していることが重要な点

In [21]:
X = np.array([1, 2])
X.shape

(2,)

\begin{eqnarray}
X=
\begin{pmatrix}
x_1 & x_2 \\
\end{pmatrix}
=
\begin{pmatrix}
1 & 2 \\
\end{pmatrix}
\end{eqnarray}

In [22]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [23]:
W.shape

(2, 3)

\begin{eqnarray}
W =
\begin{pmatrix}
y_{1,1} & y_{1, 2} \\
y_{2,1} & y_{2, 2} \\
y_{3,1} & y_{3, 2} 
\end{pmatrix}
=
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 
\end{pmatrix}
\end{eqnarray}

In [24]:
Y = np.dot(X, W)

In [25]:
print(Y)

[ 5 11 17]


\begin{eqnarray}
\begin{pmatrix}
1 & 2 
\end{pmatrix}
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{pmatrix}
=
\begin{pmatrix}
5 & 11 & 17
\end{pmatrix}
\end{eqnarray}

* ここで示したように、`np.dot`(多次元配列のドット積)を使うことで、`Y`の要素数が膨大でも一度の演算で実行ができる

| 版   | 年/月/日   |
| ---- | ---------- |
| 初版 | 2019/05/01 |