05 NumPy
=========

* `NumPy`の配列クラス(`numpy.array`)には、配列や行列の計算で用いる便利なメソッドが多く用意されている

    * ディープラーニングの実装においても、それらのメソッドを利用する

## 1. NumPyのインポート

* `NumPy`は、外部ライブラリのため、importする必要がある

In [1]:
import numpy as np

* この意味は、「`numpy`を`np`として読み込む」

* ゆえに、NumPyに関するメソッドは`np`として参照することができる

## 2. NumPy配列の生成

* NumPyの配列を作成するために、`np.array()`というメソッドを用いる

* `np.array()`：Pythonのリストを引数に取り、NumPy用の配列(`numpy.ndarray`)を作成する

In [2]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


\begin{pmatrix}
1 \\
2 \\
3 \\
\end{pmatrix}

In [3]:
type(x)

numpy.ndarray

## 3. NumPyの算術計算

* 以下に、例を示す

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [5]:
x + y

array([3., 6., 9.])

\begin{eqnarray}
\begin{pmatrix}
1 \\
2 \\
3 \end{pmatrix}
+
\begin{pmatrix}
2 \\
4 \\
6 \end{pmatrix}
=
\begin{pmatrix}
3 \\
6 \\
9 \end{pmatrix}
\end{eqnarray}

In [6]:
x - y

array([-1., -2., -3.])

\begin{eqnarray}
\begin{pmatrix}
1 \\
2 \\
3 \end{pmatrix}
-
\begin{pmatrix}
2 \\
4 \\
6 \end{pmatrix}
=
\begin{pmatrix}
-1 \\
-2 \\
-3 \end{pmatrix}
\end{eqnarray}

In [7]:
x * y

array([ 2.,  8., 18.])

\begin{eqnarray}
\begin{pmatrix}
1 \\
2 \\
3 \end{pmatrix}
\begin{pmatrix}
2 \\
4 \\
6 \end{pmatrix}
=
\begin{pmatrix}
2 \\
8 \\
18 \end{pmatrix}
\end{eqnarray}

In [8]:
x / y 

array([0.5, 0.5, 0.5])

* NumPy配列と単一の数値(スカラ値)の組み合わせで算術計算をすることもできる

    * その場合、NumPy配列の各要素とスカラ値の間で計算が行われる
    
    * この機能を、`ブロードキャスト`と呼ぶ

In [9]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

## 4. NumPyのN次元配列

* NumPyの2次元配列(行列)は、以下のように作成できる

    * ここでは、$2 \times 2$の`A`という行列を作成する
    
    * 行列`A`の形状は、`shape`で取得できる
    
    * 行列`A`の要素のデータ型は`dtype`で参照することができる

In [10]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


\begin{eqnarray}
\begin{pmatrix}
1 & 2 \\
3 & 4 \end{pmatrix}
\end{eqnarray}

In [11]:
A.shape

(2, 2)

In [12]:
A.dtype

dtype('int64')

* ここで、行列の算術計算を見てみる

    * 行列の算術演算も同じ形状の行列同士であれば、要素ごとに計算が行われる

In [13]:
B = np.array([[3,0], [0, 6]])

In [14]:
A + B

array([[ 4,  2],
       [ 3, 10]])

\begin{eqnarray}
\begin{pmatrix}
1 & 2 \\
3 & 4 \end{pmatrix}
+
\begin{pmatrix}
3 & 0 \\
0 & 6 \end{pmatrix}
=
\begin{pmatrix}
4 & 2 \\
3 & 10\end{pmatrix}
\end{eqnarray}

In [15]:
A * B

array([[ 3,  0],
       [ 0, 24]])

\begin{eqnarray}
\begin{pmatrix}
1 & 2 \\
3 & 4 \end{pmatrix}
\begin{pmatrix}
3 & 0 \\
0 & 6 \end{pmatrix}
=
\begin{pmatrix}
3 & 0 \\
0 & 24\end{pmatrix}
\end{eqnarray}

* 行列に対してスカラ値(単一の数値)で算術計算を行うことも可能

    * `ブロードキャスト`による機能

In [16]:
A * 10

array([[10, 20],
       [30, 40]])

## 5. ブロードキャスト

* NumPyでは、形状の異なる配列の演算が可能

* 例)$2 \times 2$の行列に対して、`10`というスカラ値の掛け算を行う

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10]])
A * B

array([[10, 20],
       [30, 40]])

![ブロードキャストの例1](./images/ブロードキャストの例1.png)

* 例)1次元配列である`B`が、二次元配列`A`に対して同じ形状になるよう変形して、要素ごとの計算を行う

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

![ブロードキャストの例2](./images/ブロードキャストの例2.png)

## 6. 要素へのアクセス

* 要素のインデックスは、0から始まる

In [19]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [20]:
X[0]

array([51, 55])

In [21]:
X[0][1]

55

* `for文`を使って、各要素にアクセスすることもできる

In [22]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


* NumPyは、これまで見てきたインデックス操作に加えて、配列によって各要素にアクセスすることも可能

In [23]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [24]:
# インデックスが0、2、4番目の要素を取得
X[np.array([0, 2, 4])]

array([51, 14,  0])

* 例)`X`から15以上の値を抜き出す

In [25]:
X > 15

array([ True,  True, False,  True, False, False])

In [26]:
X[X > 15]

array([51, 55, 19])

* NumPyの配列に対して不等号などの演算子を使うと、結果はbooleanの配列になる

    * ここでは、このboolearn配列を使って、配列の各要素を取り出している

| 版   | 年/月/日   |
| ---- | ---------- |
| 初版 | 2019/04/30 |