05 NumPy
=========

* `NumPy`の配列クラス(`numpy.array`)には、配列や行列の計算で用いる便利なメソッドが多く用意されている

    * ディープラーニングの実装においても、それらのメソッドを利用する

## 1. NumPyのインポート

* `NumPy`は、外部ライブラリのため、importする必要がある

In [1]:
import numpy as np

* この意味は、「`numpy`を`np`として読み込む」

* ゆえに、NumPyに関するメソッドは`np`として参照することができる

## 2. NumPy配列の生成

* NumPyの配列を作成するために、`np.array()`というメソッドを用いる

* `np.array()`：Pythonのリストを引数に取り、NumPy用の配列(`numpy.ndarray`)を作成する

In [2]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


\begin{pmatrix}
1 \\
2 \\
3 \\
\end{pmatrix}

In [3]:
type(x)

numpy.ndarray

## 3. NumPyの算術計算

* 以下に、例を示す

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [5]:
x + y

array([3., 6., 9.])

\begin{eqnarray}
\begin{pmatrix}
1 \\
2 \\
3 \end{pmatrix}
+
\begin{pmatrix}
2 \\
4 \\
6 \end{pmatrix}
=
\begin{pmatrix}
3 \\
6 \\
9 \end{pmatrix}
\end{eqnarray}

In [6]:
x - y

array([-1., -2., -3.])

\begin{eqnarray}
\begin{pmatrix}
1 \\
2 \\
3 \end{pmatrix}
-
\begin{pmatrix}
2 \\
4 \\
6 \end{pmatrix}
=
\begin{pmatrix}
-1 \\
-2 \\
-3 \end{pmatrix}
\end{eqnarray}